# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
            - { path: '^/_fos_user_context_hash', stop: true }
    
    routing_loader: false

    view:
        view_response_listener: 'force'
    
 