controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

history_list:
    path: '/history/list'
    controller: 'App\Controller\ExchangeController::getHistoryList'
    methods: ['GET']